name: random_quote
description: A new Flutter project that displays a random quote.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.0.0
  http: ^0.12.2
  meta: ^1.2.4
  equatable: ^1.2.5
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  test_coverage: ^0.5.0
  bloc_test: ^7.1.0

flutter:
  uses-material-design: true